apiVersion: apps/v1  # Each API Version defines a different set of 'objects' we can use  (controllerRevision, StatefulSet)

# kind: Pod    =  >  use to run one  or more related containers
kind: Deployment

metadata:
  name: ws-deployment   # Variable custom name

spec:
  replicas: 3       # the number of  pods running with the same identical template

  selector:
    matchLabels:   # it will look for specific label
      component: ws

  template:
    metadata:
      labels:       #  we could have multiple labels assigned to our deployment
        component: ws
#        component1: ws1
#        component2: ws2
#        component3: ws3
    spec:
      containers:
        - name: webservice
          #image: ggabmc/webservice-demo   # (Docker hub)
          image: gcr.io/ws-kubernetes-340319/webservice-demo # (GCP Container Registry)
          ports:
            - containerPort: 8080