apiVersion: apps/v1

kind: Deployment

metadata:
  name: ws-deployment

spec:
  replicas: 3    # creating 1 pod wit all the next template down here

  selector:
    matchLabels:
      component: ws

  template:
    metadata:
      labels:
        component: ws

    spec:
      containers:
        - name: webservice
          #image: ggabmc/webservice-demo   # (Docker hub)
          image: gcr.io/ws-kubernetes-331002/webservice-demo # (GCP Container Registry)
          ports:
            - containerPort: 8080