apiVersion: apps/v1

kind: Deployment

metadata:
  name: ws-deployment

spec:
  replicas: 3    # creating 1 pod wit all the next template down here

  selector:
    matchLabels:
      component: web

  template:
    metadata:
      labels:
        component: web

    spec:
      containers:
        - name: webservice
          image: ggabmc/webservice-demo
          ports:
            - containerPort: 8080